[project]
name = "findex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "savabondarenko2016", email = "savabondarenko2016@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
